# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "phusion/ubuntu-14.04-amd64"

  config.vm.define 'machine1' do |machine|
    machine.vm.hostname = 'machine1'
  end

  # Provision
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = true
    ansible.playbook = "test.yml"
    ansible.skip_tags = ENV['ANSIBLE_SKIP_TAGS']
    ansible.tags = ENV['ANSIBLE_TAGS']
    ansible.extra_vars = {
      role_name: Dir.pwd.split('/')[-2]
    }
  end
end
